name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v5.0.0"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/saj_modbus/manifest.json"

      - name: "ZIP the integration directory"
        shell: bash
        working-directory: custom_components/saj_modbus
        run: |
          set -euo pipefail
          pwd
          test -f manifest.json  # prove we're in the right folder
          ls -la
          zip -r "$GITHUB_WORKSPACE/home-assistant-saj-r6-modbus.zip" . \
            -x "**/__pycache__/*" "**/*.pyc" ".DS_Store" "*.zip"

      - name: "Verify zip structure"
        shell: bash
        run: |
          unzip -l "$GITHUB_WORKSPACE/home-assistant-saj-r6-modbus.zip" | sed -n '1,40p'
          if unzip -l "$GITHUB_WORKSPACE/home-assistant-saj-r6-modbus.zip" | awk '{print $4}' | grep -q '^custom_components/'; then
            echo "❌ Archive contains nested custom_components path; aborting."
            exit 1
          fi
          echo "✅ Zip root looks good."

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: ${{ github.workspace }}/home-assistant-saj-r6-modbus.zip
